version: '1.0'

settings:
  workspace_path: e:\DevProjects\arcgispro-yaml-pyt\workspace
  auto_create_workspace: true
  auto_sync: true

sources:
- id: basic-tools
  name: Basic Tools
  type: local
  path: e:\DevProjects\arcgispro-yaml-pyt\workspace\sources\basic-tools
  enabled: true
  last_sync: '2026-01-16T23:09:03.595213Z'
  discovered_tools: 3

toolboxes:
- id: my-spatial-tools
  name: My Spatial Analysis Tools
  path: e:\DevProjects\arcgispro-yaml-pyt\workspace\toolboxes\my_spatial_tools.pyt
  description: Custom toolbox with selected spatial analysis tools
  tools:
  - source_id: basic-tools
    tool_path: tools/spatial_analysis/buffer_analysis
    enabled: true
  - source_id: basic-tools
    tool_path: tools/spatial_analysis/clip_features
    enabled: true
  created: '2026-01-16T15:31:18.222867'
  modified: '2026-01-16T15:31:18.225960'
  auto_regenerate: true